
module.exports = [
  {
    id: 1,
    name: 'Billgates',
    surname: "Bill",
    street: "Street",
    address: "Address",
    home: "Home",
    phone: '+998111111111',
    password: 'user',
    image: 'https://img.icons8.com/plasticine/2x/user.png',
  },
  {
    id: 2,
    name: 'Anvar',
    surname: "Bill",
    street: "Street",
    address: "Address",
    home: "Home",
    phone: '+998222222222',
    password: 'user',
    image: 'https://img.icons8.com/plasticine/2x/user.png',
  },
  {
    id: 3,
    name: "G'ani",
    surname: "Bill",
    street: "Street",
    address: "Address",
    home: "Home",
    phone: '+998333333333',
    password: 'user',
    image: 'https://img.icons8.com/plasticine/2x/user.png',
  },
  {
    id: 4,
    name: 'Alisher',
    surname: "Bill",
    street: "Street",
    address: "Address",
    home: "Home",
    phone: '+998444444444',
    password: 'user',
    image: 'https://img.icons8.com/plasticine/2x/user.png',
  },
  {
    id: 5,
    name: 'Umid',
    surname: "Bill",
    street: "Street",
    address: "Address",
    home: "Home",
    phone: '+998555555555',
    password: 'user',
    image: 'https://img.icons8.com/plasticine/2x/user.png',
  },
];
