query {
  reports(where: {
    status: {
      AND: [
        { id_not: 1 }
        { id_not: 4 }
      ]
    }
  } orderBy: createdAt_DESC) {
    id
    lat
    lng
    image
    creator{
      name
      phone
    }
    createdAt
  }
}