query {
  reports(where: {
    status: {
      id: 3
    }
  } orderBy: createdAt_DESC) {
    id
    lat
    lng
    image
    creator{
      name
      phone
    }
    createdAt
  }
}