query ($id: Int!){
  reports(where: {
    AND: [
      { status: { id: 4 } },
      { comments_some: { to: { id: $id } } }
    ]
  }) {
    id
    lat
    lng
    image
    creator{
      name
      phone
    }
    createdAt
  }
}