mutation ($comment: String!, $to: ID!, $id: Int!, $date: DateTime!){
  updateReport(data: {
    deadline: $date
    status: {
      connect: {
        id: 2
      }
    }
    comments: {
      create: {
        comment: $comment
        status: {
          connect: { id: 2 }
        }
        to: {
          connect: {
            id: $to
          }
        }
      }
    }
  }, where: { id: $id }) {
    id
  }
}