query ($id: Int!){
  report(where: {
		id: $id
  }) {
    id
    lat
    lng
    image
    creator{
      name
      phone
      image
    }
    comments(orderBy: createdAt_DESC){
      comment
      status{
        id
        name
      }
      createdAt
    }
    status{
      id
      name
    }
    type{
      id
      name
    }
    deadline
    createdAt
  }
}